### ISSUE TITLE
NethServer::SSSD: can't use method port()

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5051]
The *port()* method of NethServer::SSSD perl library always raises this error:

> Can't locate object method "new" via package "URI" (perhaps you forgot to load "URI"?) at /usr/share/perl5/vendor_perl/NethServer/SSSD.pm line 133.

*Package*
nethserver-sssd-1.0.0-1.ns7.noarch

*Steps to reproduce*
Just execute:
`perl -mNethServer::SSSD -e "NethServer::SSSD->new()->port()"`

*Expected behavior*
On a machine with nethserver-directory installed, the script must output `389`.

**Comment by gsanchietti** [comment]
In nethserver-testing:
nethserver-sssd-1.0.0-1.1.g3d6ae14.ns7.noarch.rpm

**Test case**
* Check the bug is not reproducible

**Comment by dz00te** [comment]
*System and  Package Version installed*
VM KVM - Clean install of Nethserver 7b1 fully updated
Package Installed: MailServer, OpenLDAP

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-sssd-1.0.0-1.2.g9ee0721.ns7.noarch

*Test Results after update*
Installation ok, only strange line in log:
```kernel: ipt_ULOG: ULOG: fail to register logger.```

the bug is not reproducible, but there is no output from the script so I'll wait for some other info before set as verified

**Comment by gsanchietti** [comment]
> Installation ok, only strange line in log:
> kernel: ipt_ULOG: ULOG: fail to register logger.

This is a log generated by shorewall, it's cosmetic (and for now can't be disabled): http://permalink.gmane.org/gmane.comp.security.shorewall/32639

**Comment by DavidePrincipi** [comment]
@gsanchietti @dz00te could we mark this as *verified*?

**Comment by dz00te** [comment]
@gsanchietti  has clarified the issue of the log (tnx!) but I do not know if not having the output from the script is a problem or if it's the expected behaviour

**Comment by gsanchietti** [comment]
It's the expected behavior if SSSD is not configured.
We can mark this issue as verified.

**Comment by Stell0** [comment]
In nethserver-updates:
nethserver-sssd-1.0.1-1.ns7.noarch.rpm
