### ISSUE TITLE
Backup data: basic webDAV support for backups and storage stats

### ISSUE THREAD

**Issue by gsanchietti** [NethServer/dev#5235]
Implement WebDav as backend for backup data.
Also display storage utilization statistics inside the dashboard.

----

Thanks to @dnutan  for the pull request.

**Comment by gsanchietti** [comment]
Make sure to use a server with a valid SSL certificate as webDAV target, otherwise the system will fail mounting the filesystem. 

In nethserver-testing:
nethserver-backup-data-1.2.3-1.1.gac9617f.ns7.noarch.rpm

**Comment by DavidePrincipi** [comment]
I have an issue with the Samba destination: the webdav Server URL seems to be validated even if another destination is selected

![image](https://cloud.githubusercontent.com/assets/2920838/23654843/eadea19e-0332-11e7-8297-ede5a9a6ea2b.png)

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-backup-data-1.2.3-1.2.g9757873.ns7.noarch.rpm

**Comment by dz00te** [comment]
TestInProgress.. on my home firewall  working ok from some days. backup on a qnap webdav share. no https ( i need some time con configure it)

**Comment by dz00te** [comment]
*System and Package Version installed*
Test1: HP N36L - Production install of NS7.3 full updated
Test2: VM KVM - Clean install of Nethserver 7.3 fully updated

*Install Updated Package*
yum --enablerepo=nethserver-testing install nethserver-backup-data-1.2.3-1.2.g9757873.ns7.noarch

*Test Results after update*
both system tested on
webdav: local qnap nas with webdav enabled
webdavs: remote VM onf ns7 with Nextcloud11

Test1:
backup: ok
restore: ok
Test2:
backup: ok
restore: ok


*note:*
• add instruction on manual for configuration... being sure to include the note of @gsanchietti  about a valid SSL certificate 
• also note that in case of use with nextcloud webdavs, it's better to set a quota for the user used for backup, otherwise backup-data will not be able to determine how much is the storage available

**Comment by DavidePrincipi** [comment]
In nethserver-updates:
nethserver-backup-data-1.3.0-1.ns7.noarch.rpm
