### ISSUE TITLE
Optimise nethserver-mail for light machine

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5563]
This issue is here to track the discussion (and work) on the optimization of rspamd for light machine like raspberry. This is asked by @markVnl and the arm group

The services like clamd@rspamd, redis-rspamd, and rspamd are not stopped even if rspamd is no more used for spam and virus filtering.

**Comment by gsanchietti** [comment]
The real solution is not to install rspmad at all. This can be achieved using the following command:
```
yum install nethserver-mail2-server
```

Since the installation of RPMs from the Software Center is based on yum groups, we can simply create a  "Light mail server" group only for the ARM repository.
This new groups should not contain `nethserver-mail2-filter` package.

I don't think we need new code to reach this goal.

**Comment by stephdl** [comment]
the problem is not rspamd, but clamav which is not stopped even if not used @gsanchietti, actually systemd takes in consideration to start redis-rspamd and clamd@rspamd at the good time by a `Wants` but even if you stop manually the services, at the next rspamd restart all services will go up.

@markVnl  what do you think ?

**Comment by gsanchietti** [comment]
The same rule apply: Clamav is required by `nethserver-antivirus` which is required from `nethserver-mail2-filter`.

Solution: do not install `nethserver-mail2-filter`.

To avoid the restart by rspamd, you can still tweak the configuration of systemd.
But I don't think this is really necessary.

**Comment by markVnl** [comment]
I agree we can set the mail-filter package optional and not install it by default since the fixes in #5562

so the solution is not to install `nethserver-mail2-filter`

You can call me autistic, I can't fully agree with a services keeping on running for no reason or use at all. In this particular case its using about 650MB of ram. Even on a modest but normal server with 16GB this is about 4%. moreover it is (very likely) pulled from the swap every time the virus definitions are renewed. 
'- again for no reason or use at all -'

My suggestion is to put this on the "back-log" of features nice to have.

**Comment by gsanchietti** [comment]
> I can't fully agree with a services keeping on running for no reason or use at all.

I agree with you: unused services should even be installed.
But the 90% of the users want the anti-spam module enabled and working out-of-the-box, this is why the filter is included in the mail server yum group.

Added this issue as a reference in the backlog: https://github.com/orgs/NethServer/projects/1#card-12273092

**Comment by DavidePrincipi** [comment]
@gsanchietti said:
> Since the installation of RPMs from the Software Center is based on yum groups, we can simply create a "Light mail server" group only for the ARM repository.

As YUM groups are repo-specific, the ARM architecture has to re-define all groups thus it can decide how groups are composed from scratch. There's no need to change the existing group compositions.

**Comment by markVnl** [comment]
>ARM architecture has to re-define all groups thus it can decide how groups are composed from scratch. There's no need to change the existing group compositions.

Exactly and this is done:
https://github.com/markVnl/nethserver-arm-dev/commit/d5b1cabc69407e9e4fd3192a97337014491ea028
