### ISSUE TITLE
Forbid the creation of a mail domain named like the server FQDN

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5567]
**Steps to reproduce**

- Install server mail with FQDN `domain.com`
- Create a new domain mail named `sub.domain.com`
- try to send email, it is rejected with `Recipient address rejected: Access denied`
- create a mail alias to receive `stephane@sub.domain.com` to `stephane@domain.com`
- email are rejected with `Recipient address rejected: Access denied`

you can find also in maillog `warning: do not list domain prometheus.de-labrusse.fr in BOTH mydestination and virtual_alias_domains`

**Expected behavior**

I expect that a validator prohibit the usage of a subdomain of the FQDN domain of the server **when this domain is used locally to deliver email**. I cannot assume what is the usage of a domain for a remote mail server

**Actual behavior**

Actually, there is no error, the domain is created but it is not workable

**Components**

nethserver-mail-common and nethserver-mail2-common must be patched

**See also**

https://community.nethserver.org/t/mail-alias-failure/10140

----

thank @davidep and DavidG David Gordon

**Comment by gsanchietti** [comment]
The first configuration wizard doesn't allow a second-level FQDN.

Is the bug reproducible also if the FQDN is a third level name?

**Comment by DavidePrincipi** [comment]
> The first configuration wizard doesn't allow a second-level FQDN.

I can confirm, please @stephdl  fix the bug description

![image](https://user-images.githubusercontent.com/2920838/45143676-3078ef00-b1bc-11e8-967f-396c71f04a0b.png)

I also verified that Postfix accepts anything but FQDN

**Comment by DavidePrincipi** [comment]
Giacomo saied:
> The first configuration wizard doesn't allow a second-level FQDN.

I can confirm, please @stephdl  fix the bug description

![image](https://user-images.githubusercontent.com/2920838/45143676-3078ef00-b1bc-11e8-967f-396c71f04a0b.png)

----

I'm still investigating this (rare) use cases, to understand if/how to implement a correct validator.

- Server Name (FQDN) `vm5.dpnet.nethesis.it`
- Local LDAP provider, installed mail2-server
- Added `admin@` alias for `admin@dpnet.nethesis.it`
- We must enable the `SystemUserRecipientStatus` prop. Otherwise sending mail via SMTP to `something@vm5.dpnet.nethesis.it` is denied
- If email domain `vm5.dpnet.nethesis.it` is created, when a SMTP transaction starts I get `warning: do not list domain vm5.dpnet.nethesis.it in BOTH mydestination and virtual_alias_domains`
- If email domain `sub.vm5.dpnet.nethesis.it` is created I get a different warning: `warning: do not list domain sub.vm5.dpnet.nethesis.it in BOTH virtual_alias_domains and relay_domains`
- If email domain `relay.domain.tld` is created (relaying messages to another MTA) both warnings disappear. Delivery to `admin@` works. It works also for `root@vm5.dpnet.nethesis.it`

![image](https://user-images.githubusercontent.com/2920838/45148848-7dfb5900-b1c8-11e8-9bca-843d973706f3.png)

**Comment by DavidePrincipi** [comment]
Note the difference:

```text
[root@vm5 ~]# postconf  | grep '^relay_domains '
relay_domains = relay.mydomain.tld vm5.dpnet.nethesis.it
[root@vm5 ~]# postconf -d  | grep '^relay_domains '
relay_domains = $mydestination
```

I think the fix could be just to set `relay_domains = ` (empty)  -- which is the new Postfix 3 default value

http://www.postfix.org/postconf.5.html#relay_domains

**Comment by stephdl** [comment]
closing won't fix now, reopen if needed
