### ISSUE TITLE
Squid: Use the logrotate policy

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#5662]
**Steps to reproduce**

- Install nethserver-squid
- check `/etc/logrotate.d/squid`

the logrotate configuration of squid does not use the logrotate properties

**Expected behavior**

I expect that a change in the default logrotate (esmith database) affect the logrotate configuration file of squid
settings to implement

```
    Compression=disabled
    Rotate=weekly
    Times=52
```

**Actual behavior**

it is a static file.

**Components**
nethserver-squid.noarch 0:1.7.2-1.ns7

**Comment by gsanchietti** [comment]
The default logrotate configuration for Squid preserve compressed logs for 5 weeks.
Such configuration prevent Squid from fill the disk space.
Web proxy logs are big because contain a lot of information: around 350MB each week for a small office with 20/30 people.
Also if logs are added to the backup, the size of the backup itself will increase very fast.
The default logorate  configuration is best choice to avoid possible service disruptions on existing machines.

In environments where logs need to be preserved for more than 5 weeks, just manually edit the logrotate configuration `/etc/logrotate.d/squid`. Finally, remember to add `/etc/logrotate.d/squid` to the configuration backup using the custom include.

**Comment by stephdl** [comment]
> Doesn't apply to squid logs config ?

squid follows its own rule provided by the squid rpm (no custom configuration)

**Comment by jcfernandez-890825** [comment]
So if someone would want it to change Squid log retention, he/she would have to create a template. Am I right?

**Comment by gsanchietti** [comment]
@jcfernandez-890825 you just need to change the logorate configuration template, without template custom in this case.
See http://docs.nethserver.org/en/latest/web_proxy.html#logs

If it's not clear enough, we can update it :)

**Comment by jcfernandez-890825** [comment]
@gsanchietti here in Cuba all companies use proxy and it's mandatory to keeps logs for at least a year. I think it would be nice to control logs rotation with both to web UI and the CLI API. I'm aware that squids logs can grow in size quite fast, yet I think its log rotation should be included with the rest of services and its setup should be affected by this command `db configuration setprop logrotate ...`

**Comment by gsanchietti** [comment]
If we configure squid to obey to `logrotate` key, we probably have something like 2K machines blocked in next 4/5 months.
We can't afford such pain! :D

**Comment by filippocarletti** [comment]
@jcfernandez-890825 I don't know how Cuba's laws define "logs", but if you need to know who visited a website we have lightsquid reports which answer the question. There's no need to keep the details in squid/access.log.
However, if the laws request to keep squid/access.log for a year, you have a very simple way to obey: modify /etc/logrotate.d/squid according to the rules.
No custom-template is needed.
You could also develop a nethserver-cuba rpm package to install in Cuban server to adjust settings for the government.

**Comment by stephdl** [comment]
@jcfernandez-890825 you need 

nethgui (actual server-manager)
  - php (frontend)
  - perl (backend)

cockpit (next generation)
  - css,html, js (frontend)
  - perl, bash, php (backen)

I would propose to talk of this on discourse if you are interested
