### ISSUE TITLE
7.5.1804 anaconda installer panics after failing to partition drive

### ISSUE THREAD

**Issue by averyfreeman** [NethServer/dev#5683]
7.5 installer - will try 7.6 as soon as I get some time

Just wanted to report this for posterity:

Had issue creating partitions, existing partitions could not be deleted using 'reclaim space' - after 5th time I tried, installer failed with generic message and exited to command prompt.

**Expected behavior**

Anaconda installer partition manager allow me to delete partitions and allow me to create an alternative partition scheme 

**Actual behavior**

See paragraph 1

**Components**

I'm so sorry, I can't access this installation since the installer failed.  It did manage to work with unattended installer but my LVM died and now the drive is inaccessible (I'm going to try the 7.6 ISO and see if it exhibits the same behavior).  The ISO I am referring to is 7.5.1804.
**See also**

Partially hijacked thread:  https://community.nethserver.org/t/two-versions-of-php-installed/11603

----

@stephdl and the whole team, you guys are awesome.

**Comment by gsanchietti** [comment]
Anaconda is a bit tricky and doesn't always play well with reused hard disks.
If you have problems, try the CentOS standard installation (available also from NethServer ISO), then install NethServer on it.

Since this is more an upstream issue, I'm going to close it here. Feel free to continue the discussion with a new topic at https://community.nethserver.org
