### ISSUE TITLE
Public folders junk folder deleted every night

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#5842]
The Junk mail folder related to the public folders is deleted every night, loosing its content and all the possible ACL added on that folder.

**Expected behavior**

Server admins and the owner of a public folder should be able to manage those junk messages.

The "culprit" is a cron script:
```
/etc/cron.daily/nethserver-mail-spam-expunge
```
It would be sufficient to remove the fragment from line 33 to line 38:
```
    if [[ "${USER}" == vmail ]]; then
        if [[ -n "${SpamFolder}" && -d "$MDIR/.${SpamFolder}" ]]; then
            rm -rf "$MDIR/.${SpamFolder}"
        fi
        continue
    fi
```
in this way the Junk mail folder of Public folder will honor the configured general spam retention time.

**Components**

nethserver-mail-server-2.7.1-1.ns7.noarch

**See also**

https://community.nethserver.org/t/email-junk-public-folder-is-back/9020/3

**Comment by DavidePrincipi** [comment]
Release with https://github.com/NethServer/dev/issues/5837

**Comment by gsanchietti** [comment]
I think this shouldn't be considered as bug but a change of behavior.
The folder has been removed in a old commit because it can confuse the user: see [community thread](https://community.nethserver.org/t/email-public-junk-folder/6599) and the old #5294 bug. 

I agree that adding back the shared junkmail can be useful but:
- the mailbox should be present by default
- it should be accessible only from admins
- it shouldn't be deleted from the UI (NethGUI nor Cockpit)

**Comment by DavidePrincipi** [comment]
Let's move it to a new issue
