### ISSUE TITLE
Cockpit: improve httpd settings page

### ISSUE THREAD

**Issue by federicoballarini** [NethServer/dev#5991]
Add Timezone and Short Open Tag settings used by PHP scripts (e.g. timezone is used by `sogo2webtop` script).

**Proposed solution**

Add two fields into Settings page, instead of changing these values from CLI.

EDIT: Added also these fields in Virtual Host custom settings page.

**Comment by DavidePrincipi** [comment]
Please provide more information, for instance

- why setting those fields from the UI is important. You provided an example for timezone (good) but not for Short Open Tag (bad)
- a link to a feature discussion on community.nethserver.org
- what are the possible alternatives, like doing everything from the CLI

Just some thoughts of mine:

Please do not add Short Open Tag: I feel it is rarely required by PHP apps and it is quite easy to enable it as it is `PHP_INI_PERDIR`.

`date.timezone` is probably a widely required runtime parameter, but can be easily set up by other means (by the application itself) as it is `PHP_INI_ALL`. Furthermore, the `/usr/libexec/nethserver/api/system-time/update` API script already sets it to the system one, which is a good starting point IMO.

**Comment by federicoballarini** [comment]
Surely you can close it. I like the idea that you can do quite all from UI. I had some apps that works only if ShortTags are enabled: a person that starts with NethServer, doesn't know `config setprop` commands. TimeZone it's really important (one time I've imported all webtop events from SOGo with wrong timezone). If it was printed on WebServer config probably I could read that it was wrong.
Close also the PR. If you need it, the PR is ready and you can merge it.

**Comment by DavidePrincipi** [comment]
>  I like the idea that you can do quite all from UI

The definition of "quite all" is the point here. Speaking of PHP settings I want to limit the UI settings to
server resources usage. Other run time parameters are too many and too much application specific.

> I had some apps that works only if ShortTags are enabled

Short Tags are deprecated and will be removed in the next PHP version. https://wiki.php.net/rfc/deprecate_php_short_tags

> TimeZone it's really important ... If it was printed on WebServer config probably I could read that it was wrong

The default for PHP is the same of the system. Maybe we need to fix the new PHP-FPM packages to honor it.

> one time I've imported all webtop events 

The issue of time zone conversion during data migrations has to be addressed by the migration software.

>  Close also the PR. If you need it, the PR is ready and you can merge it.

I'm really sorry to not merge it because I guess the effort to write it. Please do not make the mistake again: talk with the community before starting to code. 

Furthermore, although I don't want to merge this PR here, you can develop similar features in a separate Cockpit application for "PHP advanced configurations". I think we split the config in templates and files enough to allow the integration of _almost any_ customization.
