### ISSUE TITLE
Adjust firewall after IPsec tunnel deletion

### ISSUE THREAD

**Issue by filippocarletti** [NethServer/dev#6086]
After the deletion of an IPsec tunnel, the firewall should be adjusted.
Every tunnel adds a firewall rule to block traffic when the tunnel is not established.
When the tunnel is deleted the block rule remains active.

**Steps to reproduce**

- Add an IPsec tunnel
- Look for the tunnel name in /etc/shorewall/rules
- Delete the tunnel

**Expected behavior**

The REJECT rule should be gone

**Actual behavior**

The REJECT rule is still there

**Comment by filippocarletti** [comment]
Note: after tunnel creation the firewall is adjusted thanks to the trusted-networks-modify event.
Workaround: run `signal-event firewall-adjust`

**Comment by gsanchietti** [comment]
After the `firewall-adjust, newly added tunnels will not be able to correctly create routing without a full ipsec service restart.
See https://github.com/NethServer/nethserver-ipsec-tunnels/commit/caebfc898f4103894ecbd89dc9f3b2bd467c91b3

As suggestion, we could create a specific delete event. But the delete event should do the same things of the above commit, add back the problem.

I can't see a solution if we want to preserve the feature to selectively enable tunnels implemented by #5760

**Comment by cotosso** [comment]
In fact, the problem exists, but secondary effects should be extremely rare and occur (temporarily) only if we move vpn tunnels from NethSecurity to another device (for which NethSecurity could block traffic to the remote network).

Even if we move a vpn tunnel from ipsec to openvpn when we create the OpenVPN tunnel the /etc/shorewall/rules file would be cleaned up.

This unwanted behavior would not affect security since it does not open the firewall, but rather blocks traffic.
 
The /etc/shorewall/rules file will still be fixed the first time we make changes to any component that impacts the firewall (from vpn to port forward etc.)

Leaving everything as it is allows us to remove ipsec tunnels without restarting the ipsec service (and dropping connections) and that's a good thing.

In my opinion the positive sides of the current solution are superior to the negative ones so I would leave everything as it is.

**Comment by gsanchietti** [comment]
Thank you for the detailed analysis, I'm closing this is issue as invalid.
If the problem will generate more problems in the future we could eventually re-implment the restart of ipsec every time a tunnel is created.

**WONTFIX**
