### ISSUE TITLE
2FA configuration not cleaned up after user deletion

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#6351]
If you delete a user with the 2FA enabled, its OTP configuration is not cleaned up.

**Steps to reproduce**

- install an account provider and enable `user-settings` page;
- create a user and enable 2FA for it (for cockpit and/or ssh);
- delete the user;
- try to login into cockpit or ssh with the deleted user 

**Expected behavior**

Login should fail without OTP request.

**Actual behavior**

The system asks for OTP.

**Components**

`nethserver-cockpit-1.7.12-1.ns7.noarch`
`nethserver-openssh-1.8.0-1.ns7.noarch`

-------

The issue is related to the lack of expansion of these files:
```
/etc/nethserver/otp.secret
/etc/nethserver/cockpit.otp.force
/etc/nethserver/sshd.otp.force
```
They should be expanded in case of user deletion.

Workaround:
```
signal-event otp-save
```

**Comment by gsanchietti** [comment]
When a user is deleted, why someone should try again to login with it?
Also, even if someone try to access with the deleted user, what is the problem on requesting 2FA on a deleted user?

Indeed this is an uncommon behavior, but still it's a cosmetic bug with no impact unless you want to create another user with the same username.
In this case, the new user will not be able to login again due to 2FA.
So, is this your bug? Or is it just a cosmetic thing?

**Comment by nrauso** [comment]
It happened in a couple of situation that a sysadmin wrongly deleted a user (in particular trying to fix vpn issues, for roadwarriors that use the OTP).
Actually I thought long time before to open the issue, for the same reasons you stressed out, but finally I considered that this could be a right way to manage this kind of situation: any kind of configuration that a sysadmin will do that involves the 2FA will lead to the expansion of those file - which will clean up the entry of deleted user - so it seems to me formally correct to do that directly during user deletion.

**Comment by gsanchietti** [comment]
The process on how to reset 2FA is clearly stated inside the manual: https://docs.nethserver.org/en/v7/base_system2.html#emergency-recovery

Even this seems a simple fix, it involve multiple packages: I'm still not convinced to do the changes.

What do you think @stephdl @DavidePrincipi @filippocarletti ?

**Comment by DavidePrincipi** [comment]
I'd close the bug as Invalid/Wontfix

I understand this looks bogus from the admin's perspective. However this kind of cleanups cannot be triggered with remote account providers ATM, so the available solutions works with local ones only.

I prefer to keep the limitation and improve the docs.

We already discussed how to deal with similar issue in this discussion

https://community.nethserver.org/t/change-or-not-the-users-data-deletion-policy/11173

**Comment by stephdl** [comment]
Funny bug, good shot to find it. Obviously there is no security issue, the key is deleted with the user deletion event, when it is local. However a lot of time we decided to not fix something because of the remote account provider, indeed when the remote account provider deletes an account we have no event triggered to us.

**Comment by gsanchietti** [comment]
I'm closing it as WONTIFX
