### ISSUE TITLE
fail2ban: log rotation could provoke harmless but annoying mail report to root

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#6614]
In some conditions, the log rotation of `fail2ban` could report an issue, despite the `logrotate` completed successfully its work.
The issue is absolutely harmless but it's really annoying.

**Steps to reproduce**

- Install and enable `fail2ban`
- Check its log exists (`/var/log/fail2ban.log`)
- Disable `fail2ban`
- Force the log rotation (useful command: `/usr/sbin/logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf -v -f`)

**Expected behavior**

`fail2ban` log rotation should not report any issue

**Actual behavior**

`logrotate` report an error caused by the `postrotate` script of `fail2ban`:
```
rotating pattern: /var/log/fail2ban.log  forced from command line (52 rotations)
empty log files are not rotated, old logs are removed
considering log /var/log/fail2ban.log
  log needs rotating
rotating log /var/log/fail2ban.log, log->rotateCount is 52
dateext suffix '-20211223'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
glob finding old rotated logs failed
renaming /var/log/fail2ban.log to /var/log/fail2ban.log-20211223
creating new /var/log/fail2ban.log mode = 0600 uid = 0 gid = 0
running postrotate script
2021-12-23 10:54:35,344 fail2ban                [6062]: ERROR   Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
```

When `logrotate` run through `anacron`, this issue is reported to root with an e-mail.

This happens because of the way the postrotate script run:
```
~]# cat /etc/logrotate.d/fail2ban
...
    postrotate
      /usr/bin/fail2ban-client flushlogs >/dev/null || true
    endscript
```

When `fail2ban` is disabled but its log (`/var/log/fail2ban.log`) exists, the `postrotate` script generates an error on `strerr` which is reported via e-mail.
The fix could be to redirect `strerr` output to `/dev/null`, too:
```
/usr/bin/fail2ban-client flushlogs &>/dev/null || true
```

**Components**

`fail2ban-server-0.11.2-3.el7.noarch`

**Comment by gsanchietti** [comment]
Fail2ban complains because the client can't access the server upon logrotate, this seems to me correct behavior.
If cron raises this notification when fail2ban should be running, it is pointing out a real problem.

In NethServer, the `status` property can be used to disable the service, so this kind of warning can be raised also if fail2ban has been manually disabled. This should be a temporary error. If the user doesn't want to user anymore fail2ban, the package can be removed using: `yum remove fail2ban`.

I'm marking this is as **notabug** and I'm going to close is as invalid.
